name: Deploy to SCF
on: 
  push:
    branches: [ main, develop ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: npm install -g pnpm && pnpm install

      - name: Do deploy
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          BUCKET_REGION: ${{ secrets.BUCKET_REGION }}
          FUNCTION_NAME: ${{ secrets.FUNCTION_NAME }}
          FUNCTION_NAME_STAGING: ${{ secrets.FUNCTION_NAME_STAGING }}
          SECRET_ID: ${{ secrets.SECRET_ID }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: pnpm run publish_$([[ $GITHUB_REF_NAME = "main" ]] && echo prd || echo staging)
